#!/usr/bin/env python3
"""Generate include/belongings_data.h from JS data arrays in source/http_server.cpp"""
import re, sys, os

src = open(os.path.join(os.path.dirname(__file__), 'source', 'http_server.cpp'), encoding='utf-8').read()

def extract_array(src, name):
    m = re.search(r'const ' + re.escape(name) + r'\s*=\s*\[', src)
    if not m:
        return ''
    start = m.end()
    depth = 1
    i = start
    while i < len(src) and depth > 0:
        if src[i] == '[':
            depth += 1
        elif src[i] == ']':
            depth -= 1
        i += 1
    return src[start:i-1]

def esc(s):
    return s.replace('\\', '\\\\').replace('"', '\\"')

cloth_txt  = extract_array(src, 'CLOTH_DATA')
coord_txt  = extract_array(src, 'COORD_DATA')
goods_txt  = extract_array(src, 'TREASURE_DATA')

# CLOTH_DATA: [index,colorCount,nameHash>>>0,"label","category"]
cloth_pat = re.compile(r'\[(\d+),(\d+),(\d+)>>>0,"((?:[^"\\]|\\.)*)","((?:[^"\\]|\\.)*)"\]')
cloth = cloth_pat.findall(cloth_txt)

# COORD_DATA: [saveIndex,keyHash>>>0,colorCount,"label","category"]
coord_pat = re.compile(r'\[(\d+),(\d+)>>>0,(\d+),"((?:[^"\\]|\\.)*)","((?:[^"\\]|\\.)*)"\]')
coord = coord_pat.findall(coord_txt)

# TREASURE_DATA: [nameHash>>>0,"label","type"]
goods_pat = re.compile(r'\[(\d+)>>>0,"((?:[^"\\]|\\.)*)","((?:[^"\\]|\\.)*)"\]')
goods = goods_pat.findall(goods_txt)

out = []
out.append('#pragma once')
out.append('// belongings_data.h — generated by gen_belongings_cpp.py. Do not edit manually.')
out.append('#include <cstdint>')
out.append('')
out.append('struct BlClothItem { int index; int colorCount; uint32_t nameHash; const char* label; const char* category; };')
out.append('struct BlCoordItem { int saveIndex; uint32_t keyHash; int colorCount; const char* label; };')
out.append('struct BlGoodsItem { uint32_t nameHash; const char* label; };')
out.append('')

out.append('static const BlClothItem BL_CLOTH_ITEMS[] = {')
for idx, cc, nh, lbl, cat in cloth:
    out.append(f'    {{{idx},{cc},{nh}u,"{esc(lbl)}","{esc(cat)}"}},')
out.append('};')
out.append(f'static const int BL_CLOTH_COUNT = {len(cloth)};')
out.append('')

out.append('static const BlCoordItem BL_COORD_ITEMS[] = {')
for si, kh, cc, lbl, _ in coord:
    out.append(f'    {{{si},{kh}u,{cc},"{esc(lbl)}"}},')
out.append('};')
out.append(f'static const int BL_COORD_COUNT = {len(coord)};')
out.append('')

out.append('static const BlGoodsItem BL_GOODS_ITEMS[] = {')
for nh, lbl, _ in goods:
    out.append(f'    {{{nh}u,"{esc(lbl)}"}},')
out.append('};')
out.append(f'static const int BL_GOODS_COUNT = {len(goods)};')
out.append('')

sys.stdout.buffer.write(('\n'.join(out) + '\n').encode('utf-8'))
