// AUTO-GENERATED skeleton, manual edits PRESERVED — only the AUTO-GENERATED
// section below is regenerated by tools/gen_map_data.py. Everything else is
// handwritten and safe to modify.
#pragma once

#include <cstdint>

// ── Map.sav schema constants ─────────────────────────────────────────────────
// Hashes are computed at runtime via SaveEditor::Hash("path"); we expose the
// dotted paths here so call sites read like the upstream schema.
namespace MapKeys {
    constexpr const char* FloorKeyHash       = "MapGrid.GridX.GridZ.FloorKeyHash";
    constexpr const char* GridUgcIndex       = "MapGrid.GridX.GridZ.UgcIndex";
    constexpr const char* ActorKey           = "MapObject.ActorKey";
    constexpr const char* GridPosX           = "MapObject.Location.GridPosX";
    constexpr const char* GridPosY           = "MapObject.Location.GridPosY";
    constexpr const char* LinkedMapId        = "MapObject.MapLink.LinkedMapId";
    constexpr const char* RotY               = "MapObject.MapObjectMisc.RotY";
    constexpr const char* AddGameTime        = "MapObject.MapObjectMisc.AddGameTime";
    constexpr const char* UgcId              = "MapObject.UgcObje.UgcId";
    constexpr const char* UgcExteriorId      = "MapObject.UgcObje.UgcExteriorId";
    // House.* (lives in Map.sav)
    constexpr const char* HouseMapId         = "House.MapId";
    constexpr const char* RoommateGroupName  = "House.RoommateGroupName";
    // Mii.* (lives in Mii.sav — used for resident assignment)
    constexpr const char* MiiHouseMapId      = "Mii.Location.HouseMapId";
    constexpr const char* MiiRoomIndex       = "Mii.Location.RoomIndex";
}

// Map dimensions are fixed by the game.
constexpr int MAP_WIDTH  = 120;
constexpr int MAP_HEIGHT = 80;
constexpr int MAP_TILE_COUNT = MAP_WIDTH * MAP_HEIGHT;

// ActorKey == 0 marks an empty object slot (upstream convention).
constexpr uint32_t MAP_ACTOR_EMPTY = 0u;

// ── Tile & actor metadata tables (AUTO-GENERATED in map_data.cpp) ────────────
namespace MapData {

enum ActorGroup : uint8_t {
    ACTOR_HOUSE    = 0,
    ACTOR_FACILITY = 1,
    ACTOR_DECO     = 2,
    ACTOR_ROOM     = 3,
    ACTOR_STEP     = 4,
    ACTOR_UGC      = 5,
    ACTOR_UNKNOWN  = 6,
};

struct TileInfo {
    uint32_t hash;
    const char* code;
    uint8_t r, g, b;
    uint32_t rgba;     // ABGR-packed for SDL pixel ops
    bool internal;
};

struct ActorInfo {
    uint32_t hash;
    const char* key;
    const char* label;
    uint8_t group;     // ActorGroup
    int8_t  x0, y0;    // footprint origin offset
    uint8_t w, h;      // footprint dimensions (tiles)
};

extern const TileInfo  TILE_INFO[];
extern const int       TILE_INFO_COUNT;
extern const ActorInfo ACTOR_INFO[];
extern const int       ACTOR_INFO_COUNT;

const TileInfo*  TileLookup(uint32_t hash);
const ActorInfo* ActorLookup(uint32_t hash);

} // namespace MapData
