#!/usr/bin/env python3
"""Generates LTD image-asset lookup tables and splices them into http_server.cpp.

Reads ltdimages_mapping.json (extracted from the community spreadsheet) and
emits four JS constants — LTD_CLOTH_IMG, LTD_COORD_IMG, LTD_GOODS_IMG and
LTD_TREASURE_IMG — that map our friendly item labels to the asset roots in
github.com/ltdimages/images, and inserts them into source/http_server.cpp
right before the CLOTH_DATA block.

Re-run this whenever ltdimages_mapping.json is regenerated.
"""

import json, os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MAPPING = os.path.join(ROOT, 'ltdimages_mapping.json')
SRC     = os.path.join(ROOT, 'source', 'http_server.cpp')

BS = '\\'
QT = '"'

def js_str(s):
    return s.replace(BS, BS + BS).replace(QT, BS + QT)

def emit(name, d):
    parts = []
    for k, v in sorted(d.items()):
        parts.append('"' + js_str(k) + '":"' + js_str(v) + '"')
    return 'const ' + name + '={' + ','.join(parts) + '};'

with open(MAPPING, encoding='utf-8') as f:
    M = json.load(f)

cloth_cats = ['Tops','LongTops','Legwear','Headwear','Accessories','Socks','Shoes','Costumes']
cloth = {}
for c in cloth_cats:
    cloth.update(M[c])
coord    = M['Outfits']
goods    = M.get('Goods', {})
treasure = M.get('Treasures', {})

block_js = (
    '// ── ltdimages.png lookup (auto-generated by tools/gen_ltdimg.py from\n'
    '//    ltdimages_mapping.json). Maps friendly item labels to asset roots in\n'
    '//    github.com/ltdimages/images. Append "_NN.png" for a specific color\n'
    '//    variant, or "_00.png" for the default thumbnail. ─────────────────────\n'
    + emit('LTD_CLOTH_IMG',    cloth)    + '\n'
    + emit('LTD_COORD_IMG',    coord)    + '\n'
    + emit('LTD_GOODS_IMG',    goods)    + '\n'
    + emit('LTD_TREASURE_IMG', treasure) + '\n'
)

START = '// ── ltdimages.png lookup'
END_MARK = '// ── Belongings item data ──'

with open(SRC, encoding='utf-8') as f:
    text = f.read()

if START in text:
    new = re.sub(
        r'// ── ltdimages\.png lookup[\s\S]*?const LTD_(?:COORD|GOODS|TREASURE)_IMG=\{.*?\};\n(?:const LTD_(?:GOODS|TREASURE)_IMG=\{.*?\};\n)*',
        block_js,
        text,
        count=1,
    )
else:
    idx = text.index(END_MARK)
    new = text[:idx] + block_js + text[idx:]

with open(SRC, 'w', encoding='utf-8') as f:
    f.write(new)

print(f'cloth: {len(cloth)}, coord: {len(coord)}, goods: {len(goods)}, treasure: {len(treasure)}')
print(f'inserted ~{len(block_js)} bytes into {os.path.relpath(SRC, ROOT)}')
