#!/usr/bin/env python3
"""Generate tile + actor metadata tables for the Map tab.

Reads:
  ltd-save-editor-2.5.0/src/lib/map/tiles/tiles.ts          - tile palette
  ltd-save-editor-2.5.0/src/lib/map/actors/generatedActorNames.ts - 700+ actors
  ltd-save-editor-2.5.0/src/lib/map/actors/actors.ts        - prettifyActorKey logic

Writes:
  include/map_data.h    - C++ structs + extern table decls (handwritten parts preserved)
  source/map_data.cpp   - generated C++ tables and lookup helpers
  source/http_server.cpp - JS literals spliced between markers

Re-run whenever upstream tile/actor data changes.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
UPSTREAM = os.path.join(ROOT, 'ltd-save-editor-2.5.0', 'src', 'lib', 'map')
TILES_TS = os.path.join(UPSTREAM, 'tiles', 'tiles.ts')
ACTOR_NAMES_TS = os.path.join(UPSTREAM, 'actors', 'generatedActorNames.ts')

OUT_H = os.path.join(ROOT, 'include', 'map_data.h')
OUT_CPP = os.path.join(ROOT, 'source', 'map_data.cpp')
HTTP_SRC = os.path.join(ROOT, 'source', 'http_server.cpp')


# ── Tile extraction ──────────────────────────────────────────────────────────

TILE_RE = re.compile(
    r"\{\s*hash:\s*0x([0-9a-fA-F]+)\s*,\s*"
    r"code:\s*'([^']+)'\s*,\s*"
    r"color:\s*'(#[0-9a-fA-F]+)'\s*"
    r"(?:,\s*internal:\s*(true|false)\s*)?\s*\}"
)


def parse_hex_color(s):
    """ '#RRGGBB' or '#RGB' -> (r, g, b) ints """
    s = s.lstrip('#')
    if len(s) == 3:
        s = ''.join(c * 2 for c in s)
    return int(s[0:2], 16), int(s[2:4], 16), int(s[4:6], 16)


def extract_tiles():
    with open(TILES_TS, encoding='utf-8') as f:
        src = f.read()
    out = []
    for m in TILE_RE.finditer(src):
        h, code, color, internal = m.groups()
        out.append({
            'hash': int(h, 16),
            'code': code,
            'color': color,
            'internal': internal == 'true',
        })
    return out


# ── Actor name + footprint extraction ────────────────────────────────────────

ACTOR_RE = re.compile(
    r"\[\s*0x([0-9a-fA-F]+)\s*,\s*\{\s*"
    r"key:\s*'([^']+)'\s*,\s*"
    r"category:\s*'([^']+)'\s*"
    r"\}\s*\]"
)

FOOTPRINT_RE = re.compile(
    r"\[\s*0x([0-9a-fA-F]+)\s*,\s*\{\s*"
    r"x0:\s*(-?\d+)\s*,\s*y0:\s*(-?\d+)\s*,\s*"
    r"w:\s*(\d+)\s*,\s*h:\s*(\d+)\s*,\s*"
    r"goalX:\s*(null|-?\d+)\s*,\s*goalY:\s*(null|-?\d+)\s*"
    r"\}\s*\]"
)


def group_for_category(cat):
    if cat.startswith('MapObject_Ugc_'):
        return 'ugc'
    if cat.startswith('MapObject_House_'):
        return 'house'
    if cat.startswith('MapObject_Facility_'):
        return 'facility'
    if cat.startswith('MapObject_RoomDeco'):
        return 'room'
    if cat == 'MapObject_IslandStep':
        return 'step'
    if cat.startswith('MapObject_Obje_'):
        return 'deco'
    return 'unknown'


def prettify(key):
    # Mirror prettifyActorKey from actors.ts
    m = re.match(r'^(House|Obj)Ugc(\d+)(?:_(\d+))?$', key)
    if m:
        kind = 'UGC house' if m.group(1) == 'House' else 'UGC item'
        v = f'{m.group(2)}-{m.group(3)}' if m.group(3) else m.group(2)
        return f'{kind} {v}'
    s = key
    for p in ['Obj', 'Facility', 'House', 'Room', 'Deco']:
        if s.startswith(p):
            s = s[len(p):]
            break
    s = s.replace('_', ' ')
    s = re.sub(r'([a-z0-9])([A-Z])', r'\1 \2', s)
    s = re.sub(r'\s+', ' ', s).strip()
    return s or key


GROUP_ID = {'house': 0, 'facility': 1, 'deco': 2, 'room': 3, 'step': 4, 'ugc': 5, 'unknown': 6}


def extract_actors():
    with open(ACTOR_NAMES_TS, encoding='utf-8') as f:
        src = f.read()
    names = {}
    for m in ACTOR_RE.finditer(src):
        h = int(m.group(1), 16)
        names[h] = (m.group(2), m.group(3))  # key, category
    foot = {}
    for m in FOOTPRINT_RE.finditer(src):
        h = int(m.group(1), 16)
        foot[h] = (
            int(m.group(2)), int(m.group(3)),
            int(m.group(4)), int(m.group(5)),
        )
    out = []
    for h, (key, cat) in sorted(names.items()):
        group = group_for_category(cat)
        x0, y0, w, _h = foot.get(h, (0, 0, 1, 1))
        out.append({
            'hash': h,
            'key': key,
            'label': prettify(key),
            'group': group,
            'x0': x0, 'y0': y0,
            'w': w, 'h': _h,
        })
    return out


# ── Emission helpers ─────────────────────────────────────────────────────────

def c_str(s):
    """Escape for a C string literal."""
    return s.replace('\\', '\\\\').replace('"', '\\"')


def js_str(s):
    return s.replace('\\', '\\\\').replace('"', '\\"')


def render_cpp(tiles, actors):
    lines = []
    lines.append('// AUTO-GENERATED by tools/gen_map_data.py — do not edit by hand.')
    lines.append('// Source: ltd-save-editor-2.5.0/src/lib/map/{tiles,actors}/*.ts')
    lines.append('')
    lines.append('#include "map_data.h"')
    lines.append('')
    lines.append('namespace MapData {')
    lines.append('')
    lines.append('const TileInfo TILE_INFO[] = {')
    for t in tiles:
        r, g, b = parse_hex_color(t['color'])
        rgba = (0xFF << 24) | (b << 16) | (g << 8) | r  # SDL ABGR-packed (matches packColorRGBA upstream)
        internal = 'true' if t['internal'] else 'false'
        lines.append(
            f'  {{ 0x{t["hash"]:08x}u, "{c_str(t["code"])}", '
            f'{r},{g},{b}, 0x{rgba:08x}u, {internal} }},'
        )
    lines.append('};')
    lines.append(f'const int TILE_INFO_COUNT = {len(tiles)};')
    lines.append('')
    lines.append('const ActorInfo ACTOR_INFO[] = {')
    for a in actors:
        lines.append(
            f'  {{ 0x{a["hash"]:08x}u, "{c_str(a["key"])}", "{c_str(a["label"])}", '
            f'{GROUP_ID[a["group"]]}, {a["x0"]}, {a["y0"]}, {a["w"]}, {a["h"]} }},'
        )
    lines.append('};')
    lines.append(f'const int ACTOR_INFO_COUNT = {len(actors)};')
    lines.append('')
    lines.append('const TileInfo* TileLookup(uint32_t hash) {')
    lines.append('    for (int i = 0; i < TILE_INFO_COUNT; ++i)')
    lines.append('        if (TILE_INFO[i].hash == hash) return &TILE_INFO[i];')
    lines.append('    return nullptr;')
    lines.append('}')
    lines.append('')
    lines.append('const ActorInfo* ActorLookup(uint32_t hash) {')
    lines.append('    for (int i = 0; i < ACTOR_INFO_COUNT; ++i)')
    lines.append('        if (ACTOR_INFO[i].hash == hash) return &ACTOR_INFO[i];')
    lines.append('    return nullptr;')
    lines.append('}')
    lines.append('')
    lines.append('} // namespace MapData')
    lines.append('')
    return '\n'.join(lines)


def render_header():
    return '''// AUTO-GENERATED skeleton, manual edits PRESERVED — only the AUTO-GENERATED
// section below is regenerated by tools/gen_map_data.py. Everything else is
// handwritten and safe to modify.
#pragma once

#include <cstdint>

// ── Map.sav schema constants ─────────────────────────────────────────────────
// Hashes are computed at runtime via SaveEditor::Hash("path"); we expose the
// dotted paths here so call sites read like the upstream schema.
namespace MapKeys {
    constexpr const char* FloorKeyHash       = "MapGrid.GridX.GridZ.FloorKeyHash";
    constexpr const char* GridUgcIndex       = "MapGrid.GridX.GridZ.UgcIndex";
    constexpr const char* ActorKey           = "MapObject.ActorKey";
    constexpr const char* GridPosX           = "MapObject.Location.GridPosX";
    constexpr const char* GridPosY           = "MapObject.Location.GridPosY";
    constexpr const char* LinkedMapId        = "MapObject.MapLink.LinkedMapId";
    constexpr const char* RotY               = "MapObject.MapObjectMisc.RotY";
    constexpr const char* AddGameTime        = "MapObject.MapObjectMisc.AddGameTime";
    constexpr const char* UgcId              = "MapObject.UgcObje.UgcId";
    constexpr const char* UgcExteriorId      = "MapObject.UgcObje.UgcExteriorId";
    // House.* (lives in Map.sav)
    constexpr const char* HouseMapId         = "House.MapId";
    constexpr const char* RoommateGroupName  = "House.RoommateGroupName";
    // Mii.* (lives in Mii.sav — used for resident assignment)
    constexpr const char* MiiHouseMapId      = "Mii.Location.HouseMapId";
    constexpr const char* MiiRoomIndex       = "Mii.Location.RoomIndex";
}

// Map dimensions are fixed by the game.
constexpr int MAP_WIDTH  = 120;
constexpr int MAP_HEIGHT = 80;
constexpr int MAP_TILE_COUNT = MAP_WIDTH * MAP_HEIGHT;

// ActorKey == 0 marks an empty object slot (upstream convention).
constexpr uint32_t MAP_ACTOR_EMPTY = 0u;

// ── Tile & actor metadata tables (AUTO-GENERATED in map_data.cpp) ────────────
namespace MapData {

enum ActorGroup : uint8_t {
    ACTOR_HOUSE    = 0,
    ACTOR_FACILITY = 1,
    ACTOR_DECO     = 2,
    ACTOR_ROOM     = 3,
    ACTOR_STEP     = 4,
    ACTOR_UGC      = 5,
    ACTOR_UNKNOWN  = 6,
};

struct TileInfo {
    uint32_t hash;
    const char* code;
    uint8_t r, g, b;
    uint32_t rgba;     // ABGR-packed for SDL pixel ops
    bool internal;
};

struct ActorInfo {
    uint32_t hash;
    const char* key;
    const char* label;
    uint8_t group;     // ActorGroup
    int8_t  x0, y0;    // footprint origin offset
    uint8_t w, h;      // footprint dimensions (tiles)
};

extern const TileInfo  TILE_INFO[];
extern const int       TILE_INFO_COUNT;
extern const ActorInfo ACTOR_INFO[];
extern const int       ACTOR_INFO_COUNT;

const TileInfo*  TileLookup(uint32_t hash);
const ActorInfo* ActorLookup(uint32_t hash);

} // namespace MapData
'''


def render_js(tiles, actors):
    """Emit JS literals as a single line each — easier to splice safely."""
    # Tile: keyed by hash (decimal in JS is fine; hex is more readable)
    tparts = []
    for t in tiles:
        tparts.append(
            f'{t["hash"]}:{{c:"{t["code"]}",col:"{t["color"]}",i:{1 if t["internal"] else 0}}}'
        )
    aparts = []
    for a in actors:
        aparts.append(
            f'{a["hash"]}:{{k:"{js_str(a["key"])}",l:"{js_str(a["label"])}",g:{GROUP_ID[a["group"]]},'
            f'x0:{a["x0"]},y0:{a["y0"]},w:{a["w"]},h:{a["h"]}}}'
        )
    return (
        'const MAP_TILE_INFO={' + ','.join(tparts) + '};\n' +
        'const MAP_ACTOR_INFO={' + ','.join(aparts) + '};\n' +
        "const MAP_ACTOR_GROUPS=['house','facility','deco','room','step','ugc','unknown'];\n"
    )


# ── http_server.cpp splice ───────────────────────────────────────────────────

START = '// ── MapData JS (auto-generated by tools/gen_map_data.py)'
END   = '// ── MapData JS end'


def splice_http(js_block):
    with open(HTTP_SRC, encoding='utf-8') as f:
        text = f.read()
    block = (
        f'{START} ─────────────────────────────────────\n'
        + js_block +
        f'{END} ──────────────────────────────────────────────────────────────\n'
    )
    if START in text:
        new = re.sub(
            re.escape(START) + r'[\s\S]*?' + re.escape(END) + r'[^\n]*\n',
            block,
            text,
            count=1,
        )
    else:
        # Insert right before the CLOTH_DATA / ltdimages lookup block so the
        # tables are in scope by the time the map renderer runs.
        anchor = '// ── ltdimages.png lookup'
        idx = text.index(anchor)
        new = text[:idx] + block + text[idx:]
    with open(HTTP_SRC, 'w', encoding='utf-8') as f:
        f.write(new)


# ── Main ─────────────────────────────────────────────────────────────────────

def main():
    if not os.path.exists(TILES_TS) or not os.path.exists(ACTOR_NAMES_TS):
        print(f'fatal: upstream sources not found under {UPSTREAM}', file=sys.stderr)
        sys.exit(1)

    tiles = extract_tiles()
    actors = extract_actors()
    print(f'tiles: {len(tiles)}, actors: {len(actors)}')

    # 1) The C++ header is partially generated; we only regenerate when missing
    #    or when this header has been wiped. Manual edits to the header itself
    #    aren't expected, but if you do edit it, do so above the markers below.
    if not os.path.exists(OUT_H):
        with open(OUT_H, 'w', encoding='utf-8') as f:
            f.write(render_header())
        print(f'wrote {os.path.relpath(OUT_H, ROOT)}')
    else:
        # Re-emit anyway; the header content is fully deterministic.
        with open(OUT_H, 'w', encoding='utf-8') as f:
            f.write(render_header())
        print(f'refreshed {os.path.relpath(OUT_H, ROOT)}')

    with open(OUT_CPP, 'w', encoding='utf-8') as f:
        f.write(render_cpp(tiles, actors))
    print(f'wrote {os.path.relpath(OUT_CPP, ROOT)}')

    splice_http(render_js(tiles, actors))
    print(f'spliced JS into {os.path.relpath(HTTP_SRC, ROOT)}')


if __name__ == '__main__':
    main()
